# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcppLinkage <- function(prox, isDistance = TRUE, digits = -1L, method = "arithmetic", methodPar = 0.0, isWeighted = FALSE, isVariable = TRUE) {
    .Call(`_mdendro_rcppLinkage`, prox, isDistance, digits, method, methodPar, isWeighted, isVariable)
}

